### ISSUE TITLE
Scriptfile mode "-s" broken

### ISSUE THREAD

**Issue by Kuszki** [wendlers/mpfshell#100] opened 2021-02-17 16:34 UTC
After update from version 0.9.1 to 0.9.2 "-s" option seems to be broken. Program do nothing. In version 0.9.1 this feature works great. The same script in "-c" mode (with "\n" replaced by ";" ) works fine.

Thanks for support and really nice shell.

**Comment by skorokithakis** [comment] 2021-02-17 16:40
This seems like a duplicate of #97, it would be great if you could help debug.

**Closed by skorokithakis** 2021-02-17 16:40 UTC
